[package]
name = "qa-api-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
dotenv_codegen = "0.15.0"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tracing-subscriber = { version = "0.3.18", features = ["json"] }
reqwest = { version = "0.12.7", features = ["json"] }
serde_derive = "1.0.210"
